### ISSUE TITLE
Titles scroll vertically if in UINavigationController

### ISSUE THREAD

**Issue by jeksys** [TomThorpe/UIScrollSlidingPages#23]
If you put your custom ViewController inside UINavigationController you will be able to scroll title labels vertically

```
@interface BTBViewController() <TTSlidingPagesDataSource, TTSliddingPageDelegate>
...
[[UINavigationController alloc] initWithRootViewController:[[BTBViewController alloc] init]]
```

solution is to add a line of code into TTScrollSlidingPagesController
```
topScrollView.pagingEnabled = YES;
new line ---->  topScrollView.scrollEnabled = NO;
```

**Comment by jdelman** [comment]
Trying to get this work for iOS 9, and I'm getting the vertical scrolling issue.

@kentarokai : which `viewController` are you referring to?
