### ISSUE TITLE
App crash when at the last page, scroll all the way to the left 

### ISSUE THREAD

**Issue by nbfuhao** [TomThorpe/UIScrollSlidingPages#43]
If a user is at the last page, and try to scroll all the way to the left, then the app will crash. It is because in the ```getCurrentDisplayedPage``` method, the page index can be bigger than the subview count, thus causing crash. 
Should be fixed by #42

**Comment by TomThorpe** [comment]
Thanks for fixing this as well as reporting it - it's much appreciated :-) I've merged your PR.
 
Tom
