### ISSUE TITLE
Swift Version not working 

### ISSUE THREAD

**Issue by vjujjavarapu** [TomThorpe/UIScrollSlidingPages#50]
import UIKit

class ViewController: UIViewController, TTSlidingPagesDataSource, TTSlidingPageDelegate{

   // var slider  = TTScrollSlidingPagesController()
    
    var slider : TTScrollSlidingPagesController!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        self.slider = TTScrollSlidingPagesController()
        self.slider.titleScrollerInActiveTextColour = UIColor.grayColor()
        self.slider.titleScrollerBottomEdgeColour = UIColor.darkGrayColor()
        self.slider.titleScrollerBottomEdgeHeight = 2
        
//        self.slider.hideStatusBarWhenScrolling = true
//        self.slider.zoomOutAnimationDisabled = true
        
        self.slider.dataSource = self
        self.slider.delegate = self
        self.view.backgroundColor = UIColor.blackColor()
        self.slider.view.frame = self.view.frame
        self.view.addSubview(self.slider.view)
        self.addChildViewController(self.slider)
    }

    func numberOfPagesForSlidingPagesViewController(source: TTScrollSlidingPagesController!) -> Int32 {
        return 2
    }
    
    func pageForSlidingPagesViewController(source: TTScrollSlidingPagesController!, atIndex index: Int32) -> TTSlidingPage! {
        
        var vc : UIViewController!
        switch index {
        
        case 0 :
            
                vc = TabOneViewController()
            break
        case 1 :
                vc = TabTwoViewController()
            break
        default:
            break
        }
        
       return TTSlidingPage(contentViewController: vc!)
        
    }
    
    func titleForSlidingPagesViewController(source: TTScrollSlidingPagesController!, atIndex index: Int32) -> TTSlidingPageTitle! {
        var title =  TTSlidingPageTitle()
        switch index {
        case 0 :
            title = TTSlidingPageTitle(headerText: "TabOneVC")
            break
        case 1:
            title = TTSlidingPageTitle(headerText: "TabTwoVC")
            break
            
        default:
            print("index not 0 or 1")
            break
            
        }
        return title

        
    }
    
    
    func didScrollToViewAtIndex(index: UInt) {
        print("Did scroll to view at \(index)")
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}

I have used the exact files of your TabOneViewController , And TabTwoViewController however if you run this app, the Content Flashes and goes away. Can you please check this code and let me know whats wrong. I am using "Your Demo Classes TabOne and TabTwo View Controllers"

**Comment by vjujjavarapu** [comment]
My Bridging Header -
#import "TTScrollSlidingPagesController.h"
#import "TTSlidingPage.h"
#import "TTUIScrollViewSlidingPages.h"
#import "TTSlidingPageTitle.h"
#import "TabOneViewController.h"
#import "TabTwoViewController.h"
#import "TTUITableViewZoomController.h"

**Comment by vjujjavarapu** [comment]
i got this working myself. Can you please suggest how would i take off the Zoom effect while i scroll. I want a regular transition without zoom like Groupon.

**Comment by kenchung** [comment]
@vjujjavarapu I am having the exact same problem. Do you mind sharing how you fixed the issue? ViewControllers are not showing up.

**Comment by vjujjavarapu** [comment]
Hi,

Can you specify which issue the zoom effect or getting it to work in swift?

**Comment by vjujjavarapu** [comment]
Hi,

I apologize. I have not read the full email. The solution was do not use
Tom's TabOneViewController oTabTwoViewController.

Create Subclasses of UITableViewControllers and Rest of the part should
work fine.

Create a bridging header without the TabOne and TabTwo.
